#!/bin/perl

#	Program
#		read downloaded seq file
#	History
#	2022/07/21	GLEF	1st Ver

use strict;
use warnings;

# reading protein sequences from a fasta file
my $proteinfilename = 'sequence.fasta'; #whatever in your path/folder
open(PROTEINFILE, $proteinfilename); #fh needs your attention, google filehandle if you have any questions

my @protein_sequence = <PROTEINFILE>;
print " This is the protein sequences: ", @protein_sequence;

close PROTEINFILE;

